plugin: aws_ec2

aws_access_key: AKIAXJ4BFGR66FCF5U4B
aws_secret_key: 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

regions:
  - eu-west-2

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address
